### ISSUE TITLE
Make the application responsive 

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#1]
Make the application fully responsive using **media queries**.

**Comment by Frnt-End** [comment]
@swarnarkadas I would like to work on this issue

**Comment by swarnarkadas** [comment]
@Frnt-End, I registered this project for a hackathon that'll be held soon. So, do wait for some days.

**Comment by KrunalGupta02** [comment]
i would like to work on it.

**Comment by swarnarkadas** [comment]
@KrunalGupta02, We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb.  Also, any comments before that time are not valid. So, wait till then and run the application locally.

**Comment by KrunalGupta02** [comment]
Ok so i have to comment on the issue on 15th of Feb only till date i can raise issue or not

**Comment by swarnarkadas** [comment]
@KrunalGupta02, everything related to coding will be considered on and after 00:00 on 15th February

**Comment by sandeeprawat28** [comment]
Dear mentor, please assign this issue to me.

**Comment by swarnarkadas** [comment]
@sandeeprawat28, any comments before  00:00 on 15th Feb are invalid.

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by PARASnagpal99** [comment]
I would like to work on this issue . Please assign this to me .

**Comment by swarnarkadas** [comment]
@singhalaman23, you are assigned. Fork the repo at first and also join the '#ichat_app' channel in discord.

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by singhalaman23** [comment]
> @singhalaman23, you are assigned. Fork the repo at first and also join the '#ichat_app' channel in discord.

Sure

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"
