### ISSUE TITLE
want to add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by anamikarawat2305** [swarnarkadas/ichat_app#12]
Please assign me this issue under JWOC

**Comment by swarnarkadas** [comment]
@anamikarawat2305, could you please briefly explain the issue?

**Comment by swarnarkadas** [comment]
@anamikarawat2305, could you please briefly explain the issue so that I can understand under which difficulty level it can be put

**Comment by anamikarawat2305** [comment]
@swarnarkadas as every open source project should follow some rule and regulation during the time of contribution and also have a code_of_conduct file .

**Comment by anamikarawat2305** [comment]
![image](https://user-images.githubusercontent.com/95397876/218856303-2c2bb0e1-e1f8-477e-a9ae-bde2eeb7f263.png)

**Comment by swarnarkadas** [comment]
@anamikarawat2305, you are assigned. First Fork the repo. Also, join the '#ichat_app' channel in discord.
