### ISSUE TITLE
Add Favicon to application

### ISSUE THREAD

**Issue by Monishparameswaran** [swarnarkadas/ichat_app#15]
Hey ,i would like to work on this issue under JWOC.

**Comment by Monishparameswaran** [comment]
@swarnarkadas just completed my work, i request you to please merge my PR.

**Comment by mecivil** [comment]
I want to contribute to this issue

**Comment by LuckySingh9897** [comment]
hey, I want to work on this issue

**Comment by Atul-8115** [comment]
Hello sir I want to contribute please assign me the issue

**Comment by swarnarkadas** [comment]
@mecivil, you are assigned to this issue

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC

**Comment by mecivil** [comment]
I see that the favicon is already there in the repository before you assigned the issue to me.Please see it.
