### ISSUE TITLE
Improve the documentation and setup procedure in Readme file 

### ISSUE THREAD

**Issue by singhalaman23** [swarnarkadas/ichat_app#20]
This project needs an improved documentation that contains all the procedure of how to setup this project on our local system by styling the **markdown** supported readme file.
Please assign this issue to me and also add the JWOC tag and relevant difficulty level tag.
Thankyou.

**Comment by swarnarkadas** [comment]
@singhalaman23, you are assigned to this issue.

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC
