### ISSUE TITLE
Audio is not playing when a message is received

### ISSUE THREAD

**Issue by singhalaman23** [swarnarkadas/ichat_app#22]
There is an audio file in the project which should be played whenever a message is received, but due to some bug, it's not playing. Please assign me this issue under JWOC and do add relevant labels.

**Comment by Laxmankohar** [comment]
Hey @swarnarkadas , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC

**Comment by swarnarkadas** [comment]
@Laxmankohar, You are assigned to this issue.

**Comment by Laxmankohar** [comment]
Hey @swarnarkadas , Please have a look ?
https://user-images.githubusercontent.com/73365025/219574849-58e56ee6-a122-432d-b8cf-61f694bf4bee.mp4

**Comment by swarnarkadas** [comment]
@Laxmankohar, yeah it's fine. Send PR

**Comment by Laxmankohar** [comment]
ok
