### ISSUE TITLE
Put the 'New user joined the chat' & 'User left' messages into the middle and use different colors with it

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#23]

**Comment by singhalaman23** [comment]
I would like to work on this issue under JWOC after the current issue assigned to me in this project gets resolved. Please assign it to me.

**Comment by Laxmankohar** [comment]
Hey @swarnarkadas , I would like to work on this issue under JWOC.Can you please assign it to me.

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC

**Comment by swarnarkadas** [comment]
@singhalaman23, You are assigned

**Comment by mecivil** [comment]
I want to work on this issue under JWOC
