### ISSUE TITLE
Enhance the project with better folder structuring

### ISSUE THREAD

**Issue by pooranjoyb** [swarnarkadas/ichat_app#26]
## Issues : 
The folder structuring for the project is messed up as the server and frontend directories are not properly separated. 
Also the node modules are being installed while cloning the repository.
With some minor Bugs

## FIX : 
- [x] Need to use ```.gitignore``` to ignore node-modules
- [x] Add a seperate ``src`` directory for the frontend. CSS, JS etc should be inside one ``src`` directory
- [x] Keep only one ``package.json`` file for the backend
- [x] Development server fails to start as nodemon wasn't added in the dependencies in ``package.json`` but the server starts with ``nodemon index.js``. 

Would be glad if you assign these issues to me under **JGEC Winter of Code**. @swarnarkadas @Laxmankohar

**Comment by swarnarkadas** [comment]
@pooranjoyb, you are assigned to this issue. FIrst Fork the repo

**Comment by pooranjoyb** [comment]
> @pooranjoyb, you are assigned to this issue. FIrst Fork the repo
> 

Getting into it asap!
