### ISSUE TITLE
Create a Separate chat room for separate chats

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#3]

**Comment by subratkumar46** [comment]
I would like to add this feature into the project . Please assign this issue to me .

**Comment by swarnarkadas** [comment]
We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb.So, wait till then. Also, comments before that time are not valid.

**Comment by swarnarkadas** [comment]
@subratkumar46, We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb. So, wait till then. Also, comments before that time are not valid.

**Comment by subratkumar46** [comment]
I would like to add this feature into the project . Can I start working on it now ?

**Comment by LuckySingh9897** [comment]
I would like to work on this issue

**Comment by LuckySingh9897** [comment]
I would like to work on this issue. I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by RishabhJain0721** [comment]
I would like to work on this under JWOC

**Comment by swarnarkadas** [comment]
@LuckySingh9897, You are assigned to this issue. First fork the repo.

**Comment by LuckySingh9897** [comment]
@swarnarkadas when we enter the site it asks for a name and as for this issue I have an idea while asking for the name we will also ask for the room id so then the people with the same room id can talk to each other and their chat will we visible only to persons in that same room. in this way, we can make a separate room for separate chats. Is this ok please tell me?

**Comment by swarnarkadas** [comment]
@LuckySingh9897, yeah it's ok

**Comment by swarnarkadas** [comment]
@LuckySingh9897 is the first user gonna create a room id manually and others have to enter it while joining? Then when one user enters the site there should be 2 options. Either create a room or, join the room.

**Comment by LuckySingh9897** [comment]
@swarnarkadas if the first user enters the room with id 123 then a separate chat room will become with room id 123 and if another user came and write the same room id , then only they enter the same room if they write a different id they will transfer to the different chat room. so for your question, if they write  a different id it will means automatically means to create a room with that id or if they write the same id they will join the  same room.

**Comment by swarnarkadas** [comment]
@LuckySingh9897, Ok fine.

**Comment by LuckySingh9897** [comment]
Ok sir, I will try to implement it.

**Comment by swarnarkadas** [comment]
@LuckySingh9897, If u are done with this then send PR by tomorrow morning, else I have to assign it to others.

**Comment by LuckySingh9897** [comment]
@swarnarkadas You can assign it to someone else I tried but could not solve it.

**Comment by swarnarkadas** [comment]
@deepbeatz, you are assigned

**Comment by RishabhJain0721** [comment]
@swarnarkadas I would like to work on this issue under Jwoc.

**Comment by swarnarkadas** [comment]
@mecivil, you are assigned to this issue. As time is very short, So please let me confirm if you are willing to work on it or not by tomorrow.

**Comment by mecivil** [comment]
No, I'll not be able to do so.

**Comment by RishabhJain0721** [comment]
I'll be happy to do it.

> @mecivil, you are assigned to this issue. As time is very short, So please let me confirm if you are willing to work on it or not by tomorrow.

**Comment by swarnarkadas** [comment]
@RishabhJain0721, Yes you are assigned. Fetch all the recent updates.
