### ISSUE TITLE
Bug in Active users section

### ISSUE THREAD

**Issue by RishabhJain0721** [swarnarkadas/ichat_app#35]
While updating my end to end encryption feature for the new version of your project,I came around to find out that the "Active Users" section has some bugs:
1. The name of person who has left the chat is not being removed.
2. The name of a new person joining is not being displayed on the system of person already present in the chat.

**Comment by RishabhJain0721** [comment]
I will be raising a PR on this as soon as my previous work gets done.

**Comment by swarnarkadas** [comment]
@RishabhJain0721, You are assigned to this issue.

**Comment by Laxmankohar** [comment]
Hey @swarnarkadas , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by swarnarkadas** [comment]
@RishabhJain0721, are you done with this? If yes then send PR as the time period is already over

**Comment by RishabhJain0721** [comment]
@swarnarkadas Sorry I was a bit busy due to my college sessionals.I have almost completed the task and will be raising a PR today.

**Comment by RishabhJain0721** [comment]
Hi @swarnarkadas 
I have raised a PR regarding the bugfix.Could you please review it?
