### ISSUE TITLE
[DOC] Update Readme file new features

### ISSUE THREAD

**Issue by Suryansh1720001** [swarnarkadas/ichat_app#37]
Hello admin

## Features I want to add - 
- add the contribution guidelines.
- Add the maintainer details
- Add new features for more attractiveness.
- Add the contributor details.

These are important features of the readme file of any open-source project. kindly assign me this issue.

**Comment by Suryansh1720001** [comment]
@swarnarkadas 
Any update?

**Comment by swarnarkadas** [comment]
@Suryansh1720001, I will assign this issue to you Within 2-3 days. Don't worry.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @swarnarkadas
