### ISSUE TITLE
Make User interface attractive

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#4]
Upgrade the user interface & make it as attractive as possible. You can use any CSS framework **except Bootstrap**.

**Comment by AminMusah** [comment]
@swarnarkadas I would like to work on this issue. Can you assign this to me.

**Comment by swarnarkadas** [comment]
@AminMusah, I registered this project specifically for a hackathon that'll be held soon. So, wait for some days.

**Comment by AminMusah** [comment]
@swarnarkadas okay sure thanks.

**Comment by itsshahinhere** [comment]
hello, i would like to work on this issue

**Comment by swarnarkadas** [comment]
@itsshahinhere , are you a mentee of JWOC?

**Comment by Shantanu-Meta** [comment]
Hey i am a participant in Jwoc. I would like to contribute in your project to grow its features more.

**Comment by swarnarkadas** [comment]
@Shantanu-Meta, We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb. So, wait till then. Also, any comments before that time are not valid.

**Comment by Shantanu-Meta** [comment]
Oky got it

**Comment by swarnarkadas** [comment]
@sandeeprawat28 , any comments before  00:00 on 15th Feb are invalid.

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC.

**Comment by Monishparameswaran** [comment]
Hey ,I would like to work on this issue ,please assign this to me.

**Comment by PARASnagpal99** [comment]
I would like to work on this issue .

**Comment by swarnarkadas** [comment]
@Neha00011, you are assigned. Fork the repo at first. Also, join the '#ichat_app' channel in discord.

**Comment by swarnarkadas** [comment]
@PARASnagpal99, you are assigned. Fork the repo at first. Also, join the '#ichat_app' channel in discord.

**Comment by Code1705** [comment]
I want to contribute in this issue under JWOC .

**Comment by swarnarkadas** [comment]
@PARASnagpal99, You had to send a PR within 24 hours as it is an issue with an Easy difficulty level. So, according to the rule, I am assigning this issue to others.

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC

**Comment by swarnarkadas** [comment]
@Monishparameswaran, You had to send a PR within 24 hours as it is an issue with an Easy difficulty level. So, according to the rule, I am assigning this issue to others.

**Comment by Code1705** [comment]
May I ask why am I unassigned  from this issue??

**Comment by swarnarkadas** [comment]
@Code1705, You are assigned to this issue now. Previously I had unassigned Monish before the completion of 24 hours by mistake.
First Fork the repo, before starting work.

**Comment by pooranjoyb** [comment]
@swarnarkadas Hello Mentor, I would like to work on this issue under JWOC '23! 
Would be glad if you assign me with this issue if th e time limit ends :)

**Comment by Code1705** [comment]
Ok, thanks
