### ISSUE TITLE
Add the message timing and display the sender's name along with every message.

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#5]
When anyone Sends any message, add the message timing and also display the sender's name along with every message in the Chat.

**Comment by Laxmankohar** [comment]
Hey @swarnarkadas I would like to work on this issue. Can you please assign this issue to me?

**Comment by swarnarkadas** [comment]
@Laxmankohar, We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb. So, wait till then.

**Comment by Laxmankohar** [comment]
ok

**Comment by singhalaman23** [comment]
I would like to work on this issue under JWOC
