### ISSUE TITLE
[Enhancement] Adding Mobile Responsiveness

### ISSUE THREAD

**Issue by pooranjoyb** [swarnarkadas/ichat_app#50]
# Reason/Context

## Why we need this improvement?
In this current version of the page, the mobile version of the application is broken, that needs to be fixed..

## How will this change help?
It will enhance the UI of the webpage. It will give a better and professional look to the website, hence giving a better user-experience.

### What changes have to be introduced?
Some drastic CSS changes have to be made in order to enhance the UI. 

### How could it be implemented/designed?
This can be achieved by using some frameworks like `Tailwind CSS` or `Bootstrap` or some custom CSS.

## I would like to work on this issue under JWOC 2023. Would be glad if you assign this issue to me. @swarnarkadas

**Comment by swarnarkadas** [comment]
@pooranjoyb, you are assigned. Again fetch all the recent updates.

**Comment by pooranjoyb** [comment]
Ok bhaiyaa, Sure 😃 
Please mention the difficullity label. @swarnarkadas
