### ISSUE TITLE
[Enhancement] Adding a Navbar 

### ISSUE THREAD

**Issue by pooranjoyb** [swarnarkadas/ichat_app#56]
### What changes have to be introduced?
We need to add a Navigation Bar to the Chat Application so that user get to explore more about the service such as `About Us`, `Testimonial`, `Contact Us` pages, etc.

### Will this be a breaking change?
No, it won't break any change.

### How could it be implemented/designed?
This can be achieved by adding some addition `Tailwind Css` to create a responsive navigation bar.

## I would like to work on this issue under JWOC 2023. Please assign me with this issue. @swarnarkadas 😃 👍

**Comment by swarnarkadas** [comment]
@pooranjoyb, You are assigned.
