### ISSUE TITLE
[Enhancement] Creating a Contact Us Page

### ISSUE THREAD

**Issue by pooranjoyb** [swarnarkadas/ichat_app#59]
## Outcomes : 
- The `Contact Us` page will contain a form that will let users to communicate with the Admin of the website.
- The users will be able to inform their issues or bugs directly to the Admin through filling the form.
- It will increase visitor trust. 
- Provide better customer support.

### I would like to work on this issue under JWOC 2023. Please Assign me @swarnarkadas 😄 👍

**Comment by swarnarkadas** [comment]
@pooranjoyb, you are assigned.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
