### ISSUE TITLE
Add different colours to each user's message in a specific chat

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#6]

**Comment by rsarthak** [comment]
Hey, I would love to work on this issue. Please assign this to me

**Comment by swarnarkadas** [comment]
@rsarthak, We are instructed not to assign issues before the contribution period for JWOC begins which is 15th Feb, So wait till then.

**Comment by rsarthak** [comment]
ok

**Comment by Aarav238** [comment]
i would like to work on it . @swarnarkadas

**Comment by swarnarkadas** [comment]
@Aarav238, We are instructed not to assign issues before the contribution period for JWOC begins which is 15th Feb. Also comments before that time are not valid. So, wait till then.

**Comment by Biswajit-Behera** [comment]
I want to work on this issue under JWOC.

**Comment by Biswajit-Behera** [comment]
Thank You @mnnkhndlwl
Will give you the updates and Will ask if I have any doubts.

**Comment by Biswajit-Behera** [comment]
Thank You @ swarnarkadas
Will give you the updates and Will ask if I have any doubts.

**Comment by singhalaman23** [comment]
I would like to work on this issue under JWOC

**Comment by swarnarkadas** [comment]
@Biswajit-Behera, You had to send a PR within 24 hours as it is an issue with an Easy difficulty level. So, according to the rule, I am assigning this issue to others.

**Comment by swarnarkadas** [comment]
@singhalaman23, You are assigned to this issue. I would like to suggest u fork the repo again before starting work.

**Comment by singhalaman23** [comment]
> @singhalaman23, You are assigned to this issue. I would like to suggest u fork the repo again before starting work.

Raised a PR, please review
