### ISSUE TITLE
fix  'null joinded the chat' & 'null left the chat' Problem 

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#7]
After opening another instance in another tab or on another browser, when you refresh the instance then in the first instance 'null joined the chat' message occurs. And if we delete the tab then the 'null left the chat' message occurs.

![Screenshot (259)](https://user-images.githubusercontent.com/84660268/217490557-2d43e2a9-5766-438e-a920-1aa3476bebd7.png)

**Comment by sajdakabir** [comment]
Hey i would like to work on this issue can you assign me it

**Comment by swarnarkadas** [comment]
@sajdakabir, I registered this project for an Open Source event that'll be held soon. So, do wait for some days.

**Comment by mecivil** [comment]
Hello @swarnarkadas ,
I want to work on this issue being a mentee in JWOC.
Please assign me with this issue as a part of JWOC.
