### ISSUE TITLE
Add a separate layout for the total no. of people who joined the specific room to chat

### ISSUE THREAD

**Issue by swarnarkadas** [swarnarkadas/ichat_app#8]
Add a separate layout for the total no. of people who joined the specific room to chat & make it visible which is increasing or decreasing accordingly

**Comment by Laxmankohar** [comment]
Is this issue and issue no #3 are similar?

**Comment by swarnarkadas** [comment]
@Laxmankohar, issue no #3 is the parent layout of this issue. means within a specific chat room, create a separate layout for the total no. of people who joined in that room

**Comment by CulturalProfessor** [comment]
Hey i would like to work on this can you assign it to me.

**Comment by swarnarkadas** [comment]
@CulturalProfessor, You are assigned. First Fork the repo. Also, join the '#ichat_app' channel in Discord.

**Comment by CulturalProfessor** [comment]
@swarnarkadas ok

**Comment by deepbeatz** [comment]
@swarnarkadas  I want to work on this issue under JWOC
