### ISSUE TITLE
[Enhancement] Update Testimonial Page

### ISSUE THREAD

**Issue by pooranjoyb** [swarnarkadas/ichat_app#81]
## Description

- The Testimonial page has to updated with Navigation Bar and Hamburger Menu.
- There is no footer in the Testimonial Page. It has to be added.
- The link to Testimonial page has to be added in the Navbar in all other pages, including `index.html`, `contact.html`, `about.html`, `signup.html` & `signin.html` pages.

### Please Assign me this issue under JWOC 2023. @swarnarkadas 😄

**Comment by swarnarkadas** [comment]
@pooranjoyb, Footer has been added

**Comment by pooranjoyb** [comment]
ok, will add the hamburger menu. 😄
